version: '2'

services:
  luya_composer:
    build:
      context: ./docker/composer
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./:/app
      - ./docker/env.php:/app/configs/env.php
      - ./docker/env-local-db.php:/app/configs/env-local-db.php
    command: composer install
  luya_php:
    build: ./docker/luya
    volumes:
      - ./:/app
      - ./docker/env.php:/app/configs/env.php
      - ./docker/env-local-db.php:/app/configs/env-local-db.php
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  luya_db:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE_ME
      MYSQL_DATABASE: luya_kickstarter_101
      MYSQL_USER: luya
      MYSQL_PASSWORD: CHANGE_ME
  luya_web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/env.php:/app/configs/env.php
      - ./docker/env-local-db.php:/app/configs/env-local-db.php
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
